version: '3.7'
services:
  web-vm:
    image: web-img
    ports:
      - 5550:5550
    depends_on:
      - product-vm
      - ordering-vm
      - best-selling-vm
  product-vm:
    image: product-img
    ports:
      - 5551:5551
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: db_name
    depends_on:
      - db
  ordering-vm:
    image: ordering-img
    ports:
      - 5552:5552
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: db_name
    depends_on:
      - db
  best-selling-vm:
    image: best-selling-img
    ports:
      - 5553:5553
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: db_name
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db_name
      MARIADB_USER: username
      MARIADB_PASSWORD: password
